If you are running this on Google Colab, you need to uncomment (remove the `#`) and execute the following lines to install the Pyomo package, the solver, and some helper tools. If you are running this on Binder or elsewhere (e.g. your own computer) you can ignore this.

In [1]:
# !pip install pyomo==6.4.1
# !apt install glpk-utils
# !pip install "git+https://github.com/sjpfenninger/optimisation-course.git#egg=optimutils&subdirectory=optimutils"

In [2]:
import pyomo.environ as pyo

from optimutils import summarise_results

# Assignment 2 - Mixed-integer linear programming (MILP)

This assignment is structured in two blocks: individual tasks and group tasks. The individual tasks are made of simple preliminary exercises that should be done individually before the instruction session. These are necessary/helpful for completing the group tasks. The group tasks involve the use of Python/Pyomo and consist of a complete optimization problem, which will be solved during the instructions.

# Individual tasks

## Exercise 1

From anoptimization point of view, the choice of the right optimization method or algorithm for a given problem is crucially important. The method chosen for an optimization task should largely depend on the type of the problem.

**(a)** Explain from the perspective of the optimization theory what the most important differences between Classic Economic Dispatch (CED) and Unit Commitment (UC) are.

<div style="color:red">
In  the  formulation  of  the  Classic  Economic  Dispatch  only  continuous  variables  are  used,  in the  Unit Commitment (UC) problem also discrete variables (unit is on/off) are involved.
</div>

**(b)** Explain which numerical optimization method can be applied for solving CED problems and which one for solving UC problems

<div style="color:red">
CED: LP/NLP  

UC: MILP/MINLP
</div>

## Exercise 2

Try to formulate the optimization problem for Group Task (4.a)

<div class="alert alert-block alert-info">
💡 Hint: there should be 20 decision variables in total including continuous and binary variables
</div>

<div style="color:red">

_degrees of freedom:_  
PG_ib : Power generation of unit i in block b (MW), with i=1,2,3 and b=1,2,3
PD_jk : Power demand of load j in block k (MW), with j=1,2 and k=1,2,3,4  
In total there are 17 continuous decision variables.

Because there are min and max generating levels imposed on the units, the constraints with binary variables per generation units should be added to force the optimization algorithm to consider all possible combinations of active power genarions limits. As minimum demands generally need to be supplied, no binary variables are needed in the demand constraints.  

Therefore, there are 3 binary decision variables u_1, u_2, and u_3 

_Optimization function_ - to maximize social welfare



$$  Max \qquad   SW = 20 PD_{11} + 15 PD_{12} + 7 PD_{13}            + 4 PD_{14} + 18 PD_{21} + 16 PD_{22} + 11 PD_{23} + 3 PD_{24} - (PG_{11} + 3 PG_{12} + 3,5 PG_{13} + 4,5 PG_{21} + 5 PG_{22} + 6 PG_{23} + 8 PG_{31} + 9 PG_{32} + 10 PG_{33})   $$

_Constraints:_

$$ 0 \leq PG_{ib} \leq PG_{ib}^{max} \quad \forall i,b $$
$$ 0 \leq PD_{jk} \leq PD_{jk}^{max} \quad \forall j,k $$


$$ PD_{11} + PD_{12} + PD_{13} + PD_{14} + PD_{21} + PD_{22} + PD_{23} + PD_{24} = PG_{11} + PG_{12} + PG_{13} + PG_{21} + PG_{22} + PG_{23} + PG_{31} + PG_{32} + PG_{33} $$

$$ u_i PG_i^{min} \leq \sum_{b=1}^3 PG_{ib} \leq u_i PG_i^{max} \quad \forall i $$
$$ PD_j^{min} \leq \sum_{k=1}^4 PD_{jk} \quad \forall j $$
(these constraints are actualy not present in the assignment)  

<u> Ramping </u>
$$ PG_i^0 - \sum_{b=1}^3 PG_{ib} \leq RG_i^{down} \quad \forall i $$
$$ \sum_{b=1}^3 PG_{ib} - PG_i^0 \leq RG_i^{up} \quad \forall i $$


</div>

## Exercise 3

Go to https://www.epexspot.com/en/basicspowermarket#negative-prices-q-a and answer the following questions. Complete correct answers to these questions can be found at the EPEX website.

**(a)** What are negative prices and how do they occur?  

**(b)** Are negative prices a theoretical concept or is the buyer really paid to buying electricity?

**(c)** How often do they occur?

**(d)** Are there any means to soften or prevent negative prices?

**(e)** Are final consumers benefitting from negative prices?

<div style="color:red"> 

 
 

**(a)**   

Negative prices are a price signal on the power wholesale market that occurs when a high inflexible power generation meets low demand. Inflexible power sources can’t be shut down and restarted in a quick and cost-efficient manner. Renewables do count in, as they are dependent on external factors (wind, sun). On wholesale markets, electricity prices are driven by supply and demand, which in turn are determined by several factors such as climate conditions, seasonal factors or consumption behavior. This helps to maintain the required balance. Prices fall with low demand, signaling generators to reduce output to avoid overloading the grid. On the Day-Ahead and Intraday markets of EPEX SPOT, they can thus fall below zero. In some circumstances, one may rely on these negative prices to deal with a sudden oversupply of energy and to send appropriate market signals to reduce production. In this case, producers have to compare their costs of stopping and restarting their plants with the costs of selling their energy at a negative price (which means paying instead of receiving money). If their production means are flexible enough, they will stop producing for this period of time which will prevent or buffer the negative price on the wholesale market and ease the tension on the grid.   

 
 

**(b)**   

Negative prices are not a theoretical concept. Buyers are actually getting money and electricity from sellers. However, you need to keep in mind that if a producer is willing to accept negative prices, this means it is less expensive for him to keep their power plants online than to shut them down and restart them later.   

 
 

**(c)**   

Negative prices are a comparably rare phenomenon, as several factors have to happen at the same time. However, they are nothing unusual. In Germany, where inflexible power generation from renewables is increasing, 211 hours on 39 days with negative prices were observed on the Day-Ahead market in 2019. On the Intraday market there were 241 hours with negative prices on 44 days in the same year. If these markets were not coupled, negative prices would occur more often, and price peaks would be more acute.   

 
 

**(d)**   

Liquidity –based on wide offer and demand –is key for lowering the occurrence of negative prices. This is where cross-border trading solutions come in. On the Day-Ahead market, Market Coupling provides a solution for the optimal use of cross-border capacities between two or more markets. Thanks to the Market Coupling in North-Western Europe (including France, Germany, Benelux, Great Britain, the Nordic and Baltic countries), negative prices are buffered or prevented. For instance, in the case of low or negative prices in Germany, France and Benelux, Denmark and Sweden will import electricity until the cross-border capacity is fully used or prices converge.   

   

  On the Intraday market, the trading system M7 can optimally use cross-border capacities and hence buffer volatility, which also helps to decrease the number of negative prices. As a result, the “quality” of negative prices both on the Intraday and the Day-Ahead markets today is different to the extent that they did not reach -1500 € as in 2009 before the integration process took off. 

 
 

**(e)**   

Prices on the wholesale markets reflect market fundamentals and the evolution of supply and demand. Power Exchanges like EPEX SPOT provide a transparent and secure price signal to the actors of the wholesale markets. It depends on the suppliers on the question if low or negative wholesale prices have an impact on prices for final consumers.

## Exercise 4

Consider three generating units and two demands. Each unit offers three blocks, while each demand bids four blocks. The technical characteristics of the generating units are given in the table as follows:

| Unit Data | Unit 1 | Unit 2 | Unit 3|
|:---|---:|---:|---:|
| Capacity (MW) | 30 | 25 | 25 |
| Minimum Power Output (MW) | 5 | 8 | 10 |
| Ramp up/down limit (MW/h) | 5 | 10 | 10 |
| Initial Status (on/off) | on | on | on |
| Initial power output (MW) | 10 | 15 | 10 |

Offers by generators and bids by demands are as follows:

| Offers | Unit 1 | Unit 2 | Unit 3|
|:---|---:|---:|---:|
| Block |  1 2 3  |  1 2 3   |  1 2 3   |
| Power (MW) | 5 12 13 |  8 8 9  | 10 10 5 |
| Price ($/MWh) | 1 3 3.5 | 4.5 5 6 |  8 9 10 |  




| Bids | Demand 1 | Demand 2 |
|:---|---:|---:|
| Block |  1 2 3 4 |  1 2 3 4  | 
| Energy (MWh) | 6 5 5 3 |   5 4 4 3 |
| Price ($/MWh) | 20 15 7 4 | 18 16 11 3 |

**(a)** Define the single-period auction problem as an optimization problem by specifying: 
- degrees of freedom (optimization variables)
- objective function
- constraints
- type of the optimization problem

💡 Hint: there should be 20 decision variables in total including continuous and binary variables

**(b)**  Calculate the market clearing price and the social welfare in Python for the following cases:

- Case 1: minimum power output and ramping constraints are not taken into account
- Case 2: minimum power output and ramping constrains are taken into account.

**(c)** What can you say about the producer surplus and customer surplus in both cases?

### Solutions B

### Case 1

Minimum power output and ramping constraints are not taken into account

In [3]:
m = pyo.ConcreteModel(name = "Single-period auction")
m.dual = pyo.Suffix(direction=pyo.Suffix.IMPORT)

##
# 1. Decision variables
##

m.PG11 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG12 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG13 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG21 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG22 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG23 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG31 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG32 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG33 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD11 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD12 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD13 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD14 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD21 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD22 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD23 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD24 = pyo.Var(domain=pyo.NonNegativeReals)
m.U1 = pyo.Var(domain=pyo.Binary)
m.U2 = pyo.Var(domain=pyo.Binary)
m.U3 = pyo.Var(domain=pyo.Binary)

##
# 2. Objective function
##

m.social_welfare = pyo.Objective(
    expr = (
        20 * m.PD11 + 15 * m.PD12 + 7 * m.PD13 + 4 * m.PD14 + 18 * m.PD21 + 16 * m.PD22 + 11 * m.PD23 + 3 * m.PD24 -
        (1 * m.PG11 + 3 * m.PG12+ 3.5 * m.PG13 + 4.5 * m.PG21 + 5 * m.PG22 + 6 * m.PG23 + 8 * m.PG31 + 9 * m.PG32 + 10 * m.PG33)),

    sense = pyo.maximize,
)

##
# 3. Constraints
##

# Demand and supply balance

m.demand = pyo.Constraint(expr = m.PD11 + m.PD12 + m.PD13 + m.PD14 + m.PD21 + m.PD22 + m.PD23 + m.PD24
    == m.PG11 + m.PG12 + m.PG13 + m.PG21 + m.PG22 + m.PG23 + m.PG31 + m.PG32 + m.PG33)

# Per-block demand and supply constraints
m.max_PG11 = pyo.Constraint(expr=m.PG11 <= 5)
m.max_PG12 = pyo.Constraint(expr=m.PG12 <= 12)
m.max_PG13 = pyo.Constraint(expr=m.PG13 <= 13)
m.max_PG21 = pyo.Constraint(expr=m.PG21 <= 8)
m.max_PG22 = pyo.Constraint(expr=m.PG22 <= 8)
m.max_PG23 = pyo.Constraint(expr=m.PG23 <= 9)
m.max_PG31 = pyo.Constraint(expr=m.PG31 <= 10)
m.max_PG32 = pyo.Constraint(expr=m.PG32 <= 10)
m.max_PG33 = pyo.Constraint(expr=m.PG33 <= 5)

m.max_PD11 = pyo.Constraint(expr=m.PD11 <= 6)
m.max_PD12 = pyo.Constraint(expr=m.PD12 <= 5)
m.max_PD13 = pyo.Constraint(expr=m.PD13 <= 5)
m.max_PD14 = pyo.Constraint(expr=m.PD14 <= 3)
m.max_PD21 = pyo.Constraint(expr=m.PD21 <= 5)
m.max_PD22 = pyo.Constraint(expr=m.PD22 <= 4)
m.max_PD23 = pyo.Constraint(expr=m.PD23 <= 4)
m.max_PD24 = pyo.Constraint(expr=m.PD24 <= 3)

# Per-plant minimum and maximum power output
m.binary_min_PG1 = pyo.Constraint(expr = m.U1 * 5 <= m.PG11 + m.PG12 + m.PG13)
m.binary_max_PG1 = pyo.Constraint(expr = m.PG11 + m.PG12 + m.PG13 <= m.U1 * 30)
m.binary_min_PG2 = pyo.Constraint(expr = m.U2 * 8 <= m.PG21 + m.PG22 + m.PG23)
m.binary_max_PG2 = pyo.Constraint(expr = m.PG21 + m.PG22 + m.PG23 <= m.U2 * 25)
m.binary_min_PG3 = pyo.Constraint(expr = m.U3 * 10 <= m.PG31 + m.PG32 + m.PG33)
m.binary_max_PG3 = pyo.Constraint(expr = m.PG31 + m.PG32 + m.PG33 <= m.U3 * 25)

# # Solve the problem
solver = pyo.SolverFactory('glpk')
solver.solve(m)

{'Problem': [{'Name': 'unknown', 'Lower bound': 345.5, 'Upper bound': 345.5, 'Number of objectives': 1, 'Number of constraints': 25, 'Number of variables': 21, 'Number of nonzeros': 59, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '1', 'Number of created subproblems': '1'}}, 'Error rc': 0, 'Time': 0.0070648193359375}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [4]:
summarise_results(m)

### Case 2

Minimum power output and ramping constraints are taken into account!

In [5]:
m = pyo.ConcreteModel(name = "Single-period auction")
m.dual = pyo.Suffix(direction=pyo.Suffix.IMPORT)

##
# 1. Decision variables
##

m.PG11 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG12 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG13 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG21 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG22 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG23 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG31 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG32 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG33 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD11 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD12 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD13 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD14 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD21 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD22 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD23 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD24 = pyo.Var(domain=pyo.NonNegativeReals)
m.U1 = pyo.Var(domain=pyo.Binary)
m.U2 = pyo.Var(domain=pyo.Binary)
m.U3 = pyo.Var(domain=pyo.Binary)

##
# 2. Objective function
##

m.social_welfare = pyo.Objective(
    expr = (
        20 * m.PD11 + 15 * m.PD12 + 7 * m.PD13 + 4 * m.PD14 + 18 * m.PD21 + 16 * m.PD22 + 11 * m.PD23 + 3 * m.PD24 -
        (1 * m.PG11 + 3 * m.PG12+ 3.5 * m.PG13 + 4.5 * m.PG21 + 5 * m.PG22 + 6 * m.PG23 + 8 * m.PG31 + 9 * m.PG32 + 10 * m.PG33)),

    sense = pyo.maximize,
)

##
# 3. Constraints
##

# Demand and supply balance

m.demand = pyo.Constraint(expr = m.PD11 + m.PD12 + m.PD13 + m.PD14 + m.PD21 + m.PD22 + m.PD23 + m.PD24
    == m.PG11 + m.PG12 + m.PG13 + m.PG21 + m.PG22 + m.PG23 + m.PG31 + m.PG32 + m.PG33)

# Per-block demand and supply constraints
m.max_PG11 = pyo.Constraint(expr=m.PG11 <= 5)
m.max_PG12 = pyo.Constraint(expr=m.PG12 <= 12)
m.max_PG13 = pyo.Constraint(expr=m.PG13 <= 13)
m.max_PG21 = pyo.Constraint(expr=m.PG21 <= 8)
m.max_PG22 = pyo.Constraint(expr=m.PG22 <= 8)
m.max_PG23 = pyo.Constraint(expr=m.PG23 <= 9)
m.max_PG31 = pyo.Constraint(expr=m.PG31 <= 10)
m.max_PG32 = pyo.Constraint(expr=m.PG32 <= 10)
m.max_PG33 = pyo.Constraint(expr=m.PG33 <= 5)

m.max_PD11 = pyo.Constraint(expr=m.PD11 <= 6)
m.max_PD12 = pyo.Constraint(expr=m.PD12 <= 5)
m.max_PD13 = pyo.Constraint(expr=m.PD13 <= 5)
m.max_PD14 = pyo.Constraint(expr=m.PD14 <= 3)
m.max_PD21 = pyo.Constraint(expr=m.PD21 <= 5)
m.max_PD22 = pyo.Constraint(expr=m.PD22 <= 4)
m.max_PD23 = pyo.Constraint(expr=m.PD23 <= 4)
m.max_PD24 = pyo.Constraint(expr=m.PD24 <= 3)

# Per-plant minimum and maximum power output
m.binary_min_PG1 = pyo.Constraint(expr = m.U1 * 5 <= m.PG11 + m.PG12 + m.PG13)
m.binary_max_PG1 = pyo.Constraint(expr = m.PG11 + m.PG12 + m.PG13 <= m.U1 * 30)
m.binary_min_PG2 = pyo.Constraint(expr = m.U2 * 8 <= m.PG21 + m.PG22 + m.PG23)
m.binary_max_PG2 = pyo.Constraint(expr = m.PG21 + m.PG22 + m.PG23 <= m.U2 * 25)
m.binary_min_PG3 = pyo.Constraint(expr = m.U3 * 10 <= m.PG31 + m.PG32 + m.PG33)
m.binary_max_PG3 = pyo.Constraint(expr = m.PG31 + m.PG32 + m.PG33 <= m.U3 * 25)

# Ramping

# Initial power output for each generator
PG1_0 = 10; PG2_0 = 15; PG3_0 = 10

m.ramp_down_PG1 = pyo.Constraint(expr = PG1_0 - (m.PG11 + m.PG12 + m.PG13) <= 5)
m.ramp_up_PG1 = pyo.Constraint(expr = (m.PG11 + m.PG12 + m.PG13) - PG1_0 <= 5)

m.ramp_down_PG2 = pyo.Constraint(expr = PG2_0 - (m.PG21 + m.PG22 + m.PG23) <= 10)
m.ramp_up_PG2 = pyo.Constraint(expr = (m.PG21 + m.PG22 + m.PG23) - PG2_0 <= 10)

m.ramp_down_PG3 = pyo.Constraint(expr = PG3_0 - (m.PG31 + m.PG32 + m.PG33) <= 10)
m.ramp_up_PG3 = pyo.Constraint(expr = (m.PG31 + m.PG32 + m.PG33) - PG3_0 <= 10)

# # Solve the problem
solver = pyo.SolverFactory('glpk')
solver.solve(m)

{'Problem': [{'Name': 'unknown', 'Lower bound': 327.0, 'Upper bound': 327.0, 'Number of objectives': 1, 'Number of constraints': 31, 'Number of variables': 21, 'Number of nonzeros': 77, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '5', 'Number of created subproblems': '5'}}, 'Error rc': 0, 'Time': 0.007993936538696289}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [6]:
summarise_results(m)

### Getting the market clearing price

To get the clearing price, we need to get shadow prices from the model. We want to know the shadow price of the market clearing constraint (called `market_clearing` in our formulation above).

Recall that in LP problems, the optimal solution of the dual problem gives us the shadow prices for the primal problem. The solver can do this automatically for us, but only if the problem is LP.

So, to obtain shadow prices, we turn the model from MILP to LP by fixing the integer variables from the MILP solution as model parameters with the value they had in the optimal solution. In other words, we simply replace:

```python
m.U1 = pyo.Var(domain=pyo.Binary)
m.U2 = pyo.Var(domain=pyo.Binary)
m.U3 = pyo.Var(domain=pyo.Binary)
```

with:

```python
m.U1 = 1
m.U2 = 1
m.U3 = 0
```

In [7]:
m = pyo.ConcreteModel(name = "Single-period auction")
m.dual = pyo.Suffix(direction=pyo.Suffix.IMPORT)

##
# 1. Decision variables
##

m.PG11 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG12 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG13 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG21 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG22 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG23 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG31 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG32 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG33 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD11 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD12 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD13 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD14 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD21 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD22 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD23 = pyo.Var(domain=pyo.NonNegativeReals)
m.PD24 = pyo.Var(domain=pyo.NonNegativeReals)
m.U1 = 1
m.U2 = 1
m.U3 = 0

##
# 2. Objective function
##

m.social_welfare = pyo.Objective(
    expr = (
        20 * m.PD11 + 15 * m.PD12 + 7 * m.PD13 + 4 * m.PD14 + 18 * m.PD21 + 16 * m.PD22 + 11 * m.PD23 + 3 * m.PD24 -
        (1 * m.PG11 + 3 * m.PG12+ 3.5 * m.PG13 + 4.5 * m.PG21 + 5 * m.PG22 + 6 * m.PG23 + 8 * m.PG31 + 9 * m.PG32 + 10 * m.PG33)),

    sense = pyo.maximize,
)

##
# 3. Constraints
##

# Demand and supply balance

m.demand = pyo.Constraint(expr = m.PD11 + m.PD12 + m.PD13 + m.PD14 + m.PD21 + m.PD22 + m.PD23 + m.PD24
    == m.PG11 + m.PG12 + m.PG13 + m.PG21 + m.PG22 + m.PG23 + m.PG31 + m.PG32 + m.PG33)

# Per-block demand and supply constraints
m.max_PG11 = pyo.Constraint(expr=m.PG11 <= 5)
m.max_PG12 = pyo.Constraint(expr=m.PG12 <= 12)
m.max_PG13 = pyo.Constraint(expr=m.PG13 <= 13)
m.max_PG21 = pyo.Constraint(expr=m.PG21 <= 8)
m.max_PG22 = pyo.Constraint(expr=m.PG22 <= 8)
m.max_PG23 = pyo.Constraint(expr=m.PG23 <= 9)
m.max_PG31 = pyo.Constraint(expr=m.PG31 <= 10)
m.max_PG32 = pyo.Constraint(expr=m.PG32 <= 10)
m.max_PG33 = pyo.Constraint(expr=m.PG33 <= 5)

m.max_PD11 = pyo.Constraint(expr=m.PD11 <= 6)
m.max_PD12 = pyo.Constraint(expr=m.PD12 <= 5)
m.max_PD13 = pyo.Constraint(expr=m.PD13 <= 5)
m.max_PD14 = pyo.Constraint(expr=m.PD14 <= 3)
m.max_PD21 = pyo.Constraint(expr=m.PD21 <= 5)
m.max_PD22 = pyo.Constraint(expr=m.PD22 <= 4)
m.max_PD23 = pyo.Constraint(expr=m.PD23 <= 4)
m.max_PD24 = pyo.Constraint(expr=m.PD24 <= 3)

# Per-plant minimum and maximum power output
m.binary_min_PG1 = pyo.Constraint(expr = m.U1 * 5 <= m.PG11 + m.PG12 + m.PG13)
m.binary_max_PG1 = pyo.Constraint(expr = m.PG11 + m.PG12 + m.PG13 <= m.U1 * 30)
m.binary_min_PG2 = pyo.Constraint(expr = m.U2 * 8 <= m.PG21 + m.PG22 + m.PG23)
m.binary_max_PG2 = pyo.Constraint(expr = m.PG21 + m.PG22 + m.PG23 <= m.U2 * 25)
m.binary_min_PG3 = pyo.Constraint(expr = m.U3 * 10 <= m.PG31 + m.PG32 + m.PG33)
m.binary_max_PG3 = pyo.Constraint(expr = m.PG31 + m.PG32 + m.PG33 <= m.U3 * 25)

# Ramping

# Initial power output for each generator
PG1_0 = 10; PG2_0 = 15; PG3_0 = 10

m.ramp_down_PG1 = pyo.Constraint(expr = PG1_0 - (m.PG11 + m.PG12 + m.PG13) <= 5)
m.ramp_up_PG1 = pyo.Constraint(expr = (m.PG11 + m.PG12 + m.PG13) - PG1_0 <= 5)

m.ramp_down_PG2 = pyo.Constraint(expr = PG2_0 - (m.PG21 + m.PG22 + m.PG23) <= 10)
m.ramp_up_PG2 = pyo.Constraint(expr = (m.PG21 + m.PG22 + m.PG23) - PG2_0 <= 10)

m.ramp_down_PG3 = pyo.Constraint(expr = PG3_0 - (m.PG31 + m.PG32 + m.PG33) <= 10)
m.ramp_up_PG3 = pyo.Constraint(expr = (m.PG31 + m.PG32 + m.PG33) - PG3_0 <= 10)

# # Solve the problem
solver = pyo.SolverFactory('glpk')
solver.solve(m)

{'Problem': [{'Name': 'unknown', 'Lower bound': 327.0, 'Upper bound': 327.0, 'Number of objectives': 1, 'Number of constraints': 31, 'Number of variables': 18, 'Number of nonzeros': 71, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': 0, 'Number of created subproblems': 0}}, 'Error rc': 0, 'Time': 0.0064220428466796875}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [8]:
summarise_results(m)

## A more "Pythonic" way to formulate 4.b) Case 2

<div class="alert alert-block alert-info">

💡 The following is an example of using Python to formulate the problem in a more automated, generaliseable way. With this kind of setup, you can easily extend the problem to consider, for example, additional units, simply by changing the data, without making changes to the definitions of the variables and constraints.
</div>

In [9]:
##
# 0. Model data
##

from io import StringIO
import pandas as pd
from optimutils import display_side_by_side

set_units = [1, 2, 3]
set_generator_blocks = [11, 12, 13, 21, 22, 23, 31, 32, 33]
set_demand_blocks = [11, 12, 13, 14, 21, 22, 23, 24]

units = """
Unit,Capacity,Min power out,Ramp limit,Initial power
1,30,5,5,10
2,25,8,10,15
3,25,10,10,10
"""
data_units = pd.read_csv(StringIO(units), index_col=0)

generators = """
Block,Power,Price
11,5,1
12,12,3
13,13,3.5
21,8,4.5
22,8,5
23,9,6
31,10,8
32,10,9
33,5,10
"""
data_generators = pd.read_csv(StringIO(generators), index_col=0)

demands = """
Block,Energy,Price
11,6,20
12,5,15
13,5,7
14,3,4
21,5,18
22,4,16
23,4,11
24,3,3
"""
data_demands = pd.read_csv(StringIO(demands), index_col=0)

display_side_by_side([data_units, data_generators, data_demands], ["Units","Generators","Demands"])

In [10]:
m = pyo.ConcreteModel(name = "Single-period auction")
m.dual = pyo.Suffix(direction=pyo.Suffix.IMPORT)

##
# 1. Decision variables
##

m.PG = pyo.Var(set_generator_blocks, domain=pyo.NonNegativeReals)
m.PD = pyo.Var(set_demand_blocks, domain=pyo.NonNegativeReals)
m.U = pyo.Var(set_units, domain=pyo.Binary)

##
# 2. Objective function
##

m.social_welfare = pyo.Objective(
    expr = (
        sum(data_demands.loc[j, "Price"] * m.PD[j] for j in set_demand_blocks)
        - sum(data_generators.loc[i, "Price"] * m.PG[i] for i in set_generator_blocks)
    ),
    sense = pyo.maximize,
)

##
# 3. Constraints
##

m.demand = pyo.Constraint(expr = sum(m.PD[j] for j in set_demand_blocks) == sum(m.PG[i] for i in set_generator_blocks))
m.max_PG = pyo.Constraint(set_generator_blocks, rule=lambda m, i: m.PG[i] <= data_generators.loc[i, "Power"])
m.max_PD = pyo.Constraint(set_demand_blocks, rule=lambda m, i: m.PD[i] <= data_demands.loc[i, "Energy"])


# Per-plant minimum and maximum power output
m.binary_min_PG = pyo.Constraint(
    set_units,
    rule=lambda m, i: m.U[i] * data_units.loc[i, "Min power out"] <= sum(m.PG[10*i+j] for j in [1, 2, 3])
)
m.binary_max_PG = pyo.Constraint(
    set_units,
    rule=lambda m, i: sum(m.PG[10*i+j] for j in [1, 2, 3]) <= m.U[i] * data_units.loc[i, "Capacity"]
)

# Ramping
m.ramp_down = pyo.Constraint(
    set_units,
    rule=lambda m, i: data_units.loc[i, "Initial power"] - sum(m.PG[10*i+j] for j in [1, 2, 3]) <=  data_units.loc[i, "Ramp limit"]
)
m.ramp_up = pyo.Constraint(
    set_units,
    rule=lambda m, i: sum(m.PG[10*i+j] for j in [1, 2, 3]) - data_units.loc[i, "Initial power"] <=  data_units.loc[i, "Ramp limit"]
)

# Solve the problem
solver = pyo.SolverFactory('glpk')
solver.solve(m)

{'Problem': [{'Name': 'unknown', 'Lower bound': 327.0, 'Upper bound': 327.0, 'Number of objectives': 1, 'Number of constraints': 31, 'Number of variables': 21, 'Number of nonzeros': 77, 'Sense': 'maximize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '5', 'Number of created subproblems': '5'}}, 'Error rc': 0, 'Time': 0.008298873901367188}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [11]:
summarise_results(m)

### Solution 5c

<div style="color:red">
Degrees of freedom (optimization variables) for 3 generation units in 3 blocks:  
$$ PG_{ib}, i=1,2,3 ; b=1,2,3 $$
and for 2 demands in 4 blocks:
$$ PD_{jk}, j=1,2; k=1,2,3,4 $$
In total there are 17 continuous decision variables.

Because there are min and max generating levels imposed on the units, the constraints with binary variables per generation units should be added to force the optimization algorithm to consider all possible combinations of active power generation limits. As minimum demands generally need to be supplied, no binary variables are needed in de demand constraints.

Therefore there are 3 binary decision variables $u_1, u_2$ and $u_3$.
Criterion (opt. function) – to maximize social welfare  
  
$ Max \quad SWs = 20PD_{11}+ 15PD_{12}+7PD_{13}+4PD_{14}+18PD_{21}+16PD_{22}+11PD_{23}+ 3PD_{24}–(PG_{11}+ 3PG_{12}+3,5PG_{13}+4,5PG_{21}+5PG_{22}+6PG_{23}+8PG_{31}+ 9PG_{32}+ 10PG_{33}) $

Constraints:

$$ 0 ≤ PG_{ib} ≤ PG_{MAX} \quad \forall i=1,2,3 ;b=1,2,3 $$
$$ 0 ≤ PD_{jk} ≤ PD_{MAX} \quad \forall j=1,2;k=1,2,3,4 $$

$ PD_{11} + PD_{12} + PD_{13} + PD_{14} + PD_{21} + PD_{22} + PD_{23} + PD_{24} = 
 PG_{11} + PG_{12} + PG_{13} + PG_{21} + PG_{22} + PG_{23} + PG_{31} + PG_{32} + PG_{33} $

$$ u_i PG_i^{min} \leq \sum_{b=1}^3 PG_{ib} \leq u_i PG_i^{max} \quad \forall i $$
$$ PD_j^{min} \leq \sum_{k=1}^4 PD_{jk} \quad \forall j $$
(these constraints are actualy not present in the assignment)  

<u> Ramping </u>
$$ PG_i^0 - \sum_{b=1}^3 PG_{ib} \leq RG_i^{down} \quad \forall i $$
$$ \sum_{b=1}^3 PG_{ib} - PG_i^0 \leq RG_i^{up} \quad \forall i $$

**Case 1**: In case of no ramping limits and no minimum power output the market clearing price is $4/MWh (minus Lagrange multiplier/shadow price), see the figure below. A demand block is at margin. The social welfare is $345,5

**Case 2**: When adding ramping limits and generation limits the results change to satisfy ramping constraints (Unit 1 can maximally produce 15 MW), i.e.:

---------------------
The producer surplus is the difference between what producers actually receive and what they are willing to receive. Similarly, the consumer surplus is the difference between what consumers are willing to pay and what they actually pay. The social welfare equals the sum of the consumer and the producer surpluses. In **case 1** the social welfare is $345,5;

 Producer surplus: $ (4-1)*5+(4-3)*12+(4-3,5)*13= 33,5 \\ $
Consumer surplus: $ (20-4)*6 + (18-4)*5 + (16-4)*4 + (15-4)*5 + (11-4)*4 + (7-4)*5 = 312 \\ $
Social welfare: $ 33,5+312=345,5 $
</div>

> Note: an MILP problem, it is not possible to have sensitivity report (because it is not applicable to the discrete variable ). But when you get the optimal solution of the binary variables, you can create new sheet and fix the binary variables as constant. In this case, the problem is transformed into the continuous linear programming problem, which is feasible to generate sensitivity report and get the Lagrange multiplier (-clearing price).
>

## 5) Unit Commitment with MILP

Formulate Multiperiod Unit Commitment problem for four periods to satisfy the expected demand given below:

| Period | PtD (MW) | 
|:---|---:|
| 1 | 40 | 
| 2 | 250 | 
| 3 | 300 |
| 4 | 600| 

and the following known characteristics of the three production units:

| Unit | 1 | 2 | 3 |
|:---|---:|---:|---:|
| PGmin (MW) | 0 | 0 | 0 |
| PGmax (MW) | 400 | 300 | 250|
| RampUp limit (MW/h) | 160 | 150 | 100 |
| RampDown limit (MW/h) | 160 | 150 | 100 |
| Initial Power Output (MW) | 0 | 0 | 0 |
| Initial Status | off | off | off |

The generation cost of each unit specified by the function $C_{jt}(u_{jt},P_{Gjt})$ - in other words, it depends on both whether the unit is running and how much electricity it is producing:

$C_{jt}(u_{jt},P_{Gjt})$ = $C_0$ * $u_{jt}$ + a * $P_{Gjt}$

The relevant parameters for the three units are:

| Unit | 1 | 2 | 3 |
|:---|---:|---:|---:|
| $C_0$ (﹩/h) | 100 | 200 | 300 |
| a (﹩/MWh) | 20 | 25 | 40 |

**(a)** (Case 1) In this first case, do not include ramping limits. In the problem formulation specify:
- decision variables (degrees of freedom),
- objective function
- the constraints
- type of optimization problem  

After formulating it, implement and solve the problem with Python.

In [12]:
m = pyo.ConcreteModel(name = "Unit commitment")
m.dual = pyo.Suffix(direction=pyo.Suffix.IMPORT)

##
# 1. Decision variables
##


m.U11 = pyo.Var(domain=pyo.Binary)
m.U12 = pyo.Var(domain=pyo.Binary)
m.U13 = pyo.Var(domain=pyo.Binary)
m.U14 = pyo.Var(domain=pyo.Binary)
m.U21 = pyo.Var(domain=pyo.Binary)
m.U22 = pyo.Var(domain=pyo.Binary)
m.U23 = pyo.Var(domain=pyo.Binary)
m.U24 = pyo.Var(domain=pyo.Binary)
m.U31 = pyo.Var(domain=pyo.Binary)
m.U32 = pyo.Var(domain=pyo.Binary)
m.U33 = pyo.Var(domain=pyo.Binary)
m.U34 = pyo.Var(domain=pyo.Binary)

m.PG11 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG12 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG13 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG14 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG21 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG22 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG23 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG24 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG31 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG32 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG33 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG34 = pyo.Var(domain=pyo.NonNegativeReals)


##
# 2. Objective function
##

Cost11 = 100 * m.U11 + 20 * m.PG11
Cost12 = 100 * m.U12 + 20 * m.PG12
Cost13 = 100 * m.U13 + 20 * m.PG13
Cost14 = 100 * m.U14 + 20 * m.PG14
Cost21 = 200 * m.U21 + 25 * m.PG21
Cost22 = 200 * m.U22 + 25 * m.PG22
Cost23 = 200 * m.U23 + 25 * m.PG23
Cost24 = 200 * m.U24 + 25 * m.PG24
Cost31 = 300 * m.U31 + 40 * m.PG31
Cost32 = 300 * m.U32 + 40 * m.PG32
Cost33 = 300 * m.U33 + 40 * m.PG33
Cost34 = 300 * m.U34 + 40 * m.PG34

     
m.cost = pyo.Objective(
    expr = (Cost11 + Cost12 + Cost13 + Cost14 + Cost21 + Cost22 + Cost23 + Cost24 + Cost31 +Cost32 + Cost33 + Cost34), 
    sense = pyo.minimize,
)

##
# 3. Constraints
##

# Demand constraint for each period
m.demand1 = pyo.Constraint(expr= m.PG11 + m.PG21 + m.PG31 == 40)
m.demand2 = pyo.Constraint(expr= m.PG12 + m.PG22 + m.PG32 == 250)
m.demand3 = pyo.Constraint(expr= m.PG13 + m.PG23 + m.PG33 == 300)
m.demand4 = pyo.Constraint(expr= m.PG14 + m.PG24 + m.PG34 == 600)

# Per-block demand and supply constraints
m.max_PG11 = pyo.Constraint(expr=m.PG11 <= 400 * m.U11)
m.max_PG12 = pyo.Constraint(expr=m.PG12 <= 400 * m.U12)
m.max_PG13 = pyo.Constraint(expr=m.PG13 <= 400 * m.U13)
m.max_PG14 = pyo.Constraint(expr=m.PG14 <= 400 * m.U14)
m.max_PG21 = pyo.Constraint(expr=m.PG21 <= 300 * m.U21)
m.max_PG22 = pyo.Constraint(expr=m.PG22 <= 300 * m.U22)
m.max_PG23 = pyo.Constraint(expr=m.PG23 <= 300 * m.U23)
m.max_PG24 = pyo.Constraint(expr=m.PG24 <= 300 * m.U24)
m.max_PG31 = pyo.Constraint(expr=m.PG31 <= 250 * m.U31)
m.max_PG32 = pyo.Constraint(expr=m.PG32 <= 250 * m.U32)
m.max_PG33 = pyo.Constraint(expr=m.PG33 <= 250 * m.U33)
m.max_PG34 = pyo.Constraint(expr=m.PG34 <= 250 * m.U34)


# Solve the problem
solver = pyo.SolverFactory('glpk')
solver.solve(m)

{'Problem': [{'Name': 'unknown', 'Lower bound': 25400.0, 'Upper bound': 25400.0, 'Number of objectives': 1, 'Number of constraints': 17, 'Number of variables': 25, 'Number of nonzeros': 37, 'Sense': 'minimize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '3', 'Number of created subproblems': '3'}}, 'Error rc': 0, 'Time': 0.008348941802978516}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [13]:
summarise_results(m)

**(b)** (Case 2) Building on the problem formulation and Python implementation of 5.a, we want to consider an additional case: the unit commitment problem from case 1, but including ramping limits.

### Case 2

In [14]:
m = pyo.ConcreteModel(name = "Unit commitment including ramping limits")
m.dual = pyo.Suffix(direction=pyo.Suffix.IMPORT)

##
# 1. Decision variables
##


m.U11 = pyo.Var(domain=pyo.Binary)
m.U12 = pyo.Var(domain=pyo.Binary)
m.U13 = pyo.Var(domain=pyo.Binary)
m.U14 = pyo.Var(domain=pyo.Binary)
m.U21 = pyo.Var(domain=pyo.Binary)
m.U22 = pyo.Var(domain=pyo.Binary)
m.U23 = pyo.Var(domain=pyo.Binary)
m.U24 = pyo.Var(domain=pyo.Binary)
m.U31 = pyo.Var(domain=pyo.Binary)
m.U32 = pyo.Var(domain=pyo.Binary)
m.U33 = pyo.Var(domain=pyo.Binary)
m.U34 = pyo.Var(domain=pyo.Binary)

m.PG11 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG12 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG13 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG14 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG21 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG22 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG23 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG24 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG31 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG32 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG33 = pyo.Var(domain=pyo.NonNegativeReals)
m.PG34 = pyo.Var(domain=pyo.NonNegativeReals)


##
# 2. Objective function
##

Cost11 = 100 * m.U11 + 20 * m.PG11
Cost12 = 100 * m.U12 + 20 * m.PG12
Cost13 = 100 * m.U13 + 20 * m.PG13
Cost14 = 100 * m.U14 + 20 * m.PG14
Cost21 = 200 * m.U21 + 25 * m.PG21
Cost22 = 200 * m.U22 + 25 * m.PG22
Cost23 = 200 * m.U23 + 25 * m.PG23
Cost24 = 200 * m.U24 + 25 * m.PG24
Cost31 = 300 * m.U31 + 40 * m.PG31
Cost32 = 300 * m.U32 + 40 * m.PG32
Cost33 = 300 * m.U33 + 40 * m.PG33
Cost34 = 300 * m.U34 + 40 * m.PG34

     
m.cost = pyo.Objective(
    expr = (Cost11 + Cost12 + Cost13 + Cost14 + Cost21 + Cost22 + Cost23 + Cost24 + Cost31 +Cost32 + Cost33 + Cost34), 
    sense = pyo.minimize,
)

##
# 3. Constraints
##

# Demand constraint for each period
m.demand1 = pyo.Constraint(expr= m.PG11 + m.PG21 + m.PG31 == 40)
m.demand2 = pyo.Constraint(expr= m.PG12 + m.PG22 + m.PG32 == 250)
m.demand3 = pyo.Constraint(expr= m.PG13 + m.PG23 + m.PG33 == 300)
m.demand4 = pyo.Constraint(expr= m.PG14 + m.PG24 + m.PG34 == 600)

# Per-block demand and supply constraints
m.max_PG11 = pyo.Constraint(expr=m.PG11 <= 400 * m.U11)
m.max_PG12 = pyo.Constraint(expr=m.PG12 <= 400 * m.U12)
m.max_PG13 = pyo.Constraint(expr=m.PG13 <= 400 * m.U13)
m.max_PG14 = pyo.Constraint(expr=m.PG14 <= 400 * m.U14)
m.max_PG21 = pyo.Constraint(expr=m.PG21 <= 300 * m.U21)
m.max_PG22 = pyo.Constraint(expr=m.PG22 <= 300 * m.U22)
m.max_PG23 = pyo.Constraint(expr=m.PG23 <= 300 * m.U23)
m.max_PG24 = pyo.Constraint(expr=m.PG24 <= 300 * m.U24)
m.max_PG31 = pyo.Constraint(expr=m.PG31 <= 250 * m.U31)
m.max_PG32 = pyo.Constraint(expr=m.PG32 <= 250 * m.U32)
m.max_PG33 = pyo.Constraint(expr=m.PG33 <= 250 * m.U33)
m.max_PG34 = pyo.Constraint(expr=m.PG34 <= 250 * m.U34)

# Ramping constraints
# (you could solve the problem in more pythonic way)

# Initial power output for each generator
PG1_0 = 10; PG2_0 = 15; PG3_0 = 10

# Ramp down for unit 1
m.ramp_down_PG11 = pyo.Constraint(expr = PG1_0 - m.PG11 <= 160)
m.ramp_down_PG12 = pyo.Constraint(expr = m.PG11 - m.PG12 <= 160)
m.ramp_down_PG13 = pyo.Constraint(expr = m.PG12- m.PG13<= 160)
m.ramp_down_PG14 = pyo.Constraint(expr = m.PG13 - m.PG14 <= 160)

# Ramp up for unit 1
m.ramp_up_PG11 = pyo.Constraint(expr = m.PG11 - PG1_0 <= 160)
m.ramp_up_PG12 = pyo.Constraint(expr = m.PG12 - m.PG11 <= 160)
m.ramp_up_PG13 = pyo.Constraint(expr = m.PG13 - m.PG12 <= 160)
m.ramp_up_PG14 = pyo.Constraint(expr = m.PG14 - m.PG13 <= 160)

# Ramp down for unit 2
m.ramp_down_PG21 = pyo.Constraint(expr = PG2_0 - m.PG21 <= 150)
m.ramp_down_PG22 = pyo.Constraint(expr = m.PG21 - m.PG22 <= 150)
m.ramp_down_PG23 = pyo.Constraint(expr = m.PG22- m.PG23<= 150)
m.ramp_down_PG24 = pyo.Constraint(expr = m.PG23 - m.PG24 <= 150)

# Ramp up for unit 2
m.ramp_up_PG21 = pyo.Constraint(expr = m.PG21 - PG2_0 <= 150)
m.ramp_up_PG22 = pyo.Constraint(expr = m.PG22 - m.PG21 <= 150)
m.ramp_up_PG23 = pyo.Constraint(expr = m.PG23 - m.PG22 <= 150)
m.ramp_up_PG24 = pyo.Constraint(expr = m.PG24 - m.PG23 <= 150)

# Ramp down for unit 3
m.ramp_down_PG31 = pyo.Constraint(expr = PG3_0 - m.PG31 <= 100)
m.ramp_down_PG32 = pyo.Constraint(expr = m.PG31 - m.PG32 <= 100)
m.ramp_down_PG33 = pyo.Constraint(expr = m.PG32- m.PG33<= 100)
m.ramp_down_PG34 = pyo.Constraint(expr = m.PG33 - m.PG34 <= 100)

# Ramp up for unit 3
m.ramp_up_PG31 = pyo.Constraint(expr = m.PG31 - PG3_0 <= 100)
m.ramp_up_PG32 = pyo.Constraint(expr = m.PG32 - m.PG31 <= 100)
m.ramp_up_PG33 = pyo.Constraint(expr = m.PG33 - m.PG32 <= 100)
m.ramp_up_PG34 = pyo.Constraint(expr = m.PG34 - m.PG33 <= 100)


# Solve the problem
solver = pyo.SolverFactory('glpk')
solver.solve(m)

{'Problem': [{'Name': 'unknown', 'Lower bound': 26300.0, 'Upper bound': 26300.0, 'Number of objectives': 1, 'Number of constraints': 41, 'Number of variables': 25, 'Number of nonzeros': 79, 'Sense': 'minimize'}], 'Solver': [{'Status': 'ok', 'Termination condition': 'optimal', 'Statistics': {'Branch and bound': {'Number of bounded subproblems': '11', 'Number of created subproblems': '11'}}, 'Error rc': 0, 'Time': 0.007444858551025391}], 'Solution': [OrderedDict([('number of solutions', 0), ('number of solutions displayed', 0)])]}

In [15]:
summarise_results(m)

**(c)** Compare the results across the two cases. How does adding ramping limits and a reserve constraint influence the dispatch schedule for the three units across the four time steps?

<div style="color:red">

Including ramping limit, constraints result in a higher cost (26,300) and changes to the unit commitment. In this case, unit 2 is committed during period 2,3 since there is a ramping limit for unit 1.

</div>